<x-layout.layout>
    <x-slot name="title">Reports - XCODERA</x-slot>

    <div class="space-y-6">
        <!-- Page Header -->
        <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
                <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Reports</h1>
                <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">View and analyze various reports for your dashboard</p>
            </div>
            <x-ui.button variant="primary">
                <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
                </svg>
                Generate Report
            </x-ui.button>
        </div>

        <!-- Report Filters -->
        <x-ui.card>
            <div class="flex flex-col sm:flex-row gap-4">
                <div class="flex-1">
                    <x-utils.searchbar placeholder="Search reports..." />
                </div>
                <x-form.select name="report_type" :options="['all' => 'All Types', 'sales' => 'Sales', 'users' => 'Users', 'revenue' => 'Revenue', 'traffic' => 'Traffic']" />
                <x-form.select name="period" :options="['today' => 'Today', 'week' => 'This Week', 'month' => 'This Month', 'quarter' => 'This Quarter', 'year' => 'This Year']" />
            </div>
        </x-ui.card>

        <!-- Summary Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <x-data.stat-card
                title="Total Revenue"
                value="$24,580"
                change="+12.5%"
                changeType="increase"
                icon='<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>'
                description="Compared to last month"
            />
            <x-data.stat-card
                title="New Users"
                value="1,248"
                change="+8.2%"
                changeType="increase"
                icon='<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" /></svg>'
                description="Compared to last month"
            />
            <x-data.stat-card
                title="Avg. Session"
                value="5m 32s"
                change="-2.1%"
                changeType="decrease"
                icon='<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>'
                description="Compared to last month"
            />
            <x-data.stat-card
                title="Conversion Rate"
                value="4.8%"
                change="+1.7%"
                changeType="increase"
                icon='<svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>'
                description="Compared to last month"
            />
        </div>

        <!-- Charts Section -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <!-- Revenue Chart -->
            <x-data.chart-card title="Revenue Overview" description="Monthly revenue trend">
                <canvas id="revenueChart" class="h-80"></canvas>
            </x-data.chart-card>

            <!-- Users Chart -->
            <x-data.chart-card title="Users Growth" description="New users per month">
                <canvas id="usersChart" class="h-80"></canvas>
            </x-data.chart-card>
        </div>

        <!-- Report Table -->
        <x-ui.card>
            <x-data.table
                :headers="[
                    ['label' => 'Report', 'sortable' => true],
                    ['label' => 'Date', 'sortable' => true],
                    ['label' => 'Status', 'sortable' => false],
                    ['label' => 'Generated By', 'sortable' => true],
                    ['label' => 'Actions', 'sortable' => false],
                ]"
                :rows="[
                    [
                        '<span class=\'font-medium text-gray-900 dark:text-white\'>Monthly Sales Report</span><br><span class=\'text-sm text-gray-500 dark:text-gray-400\'>Detailed sales analysis for October</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Oct 1, 2024</span>',
                        '<span class=\'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400\'>Completed</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Admin User</span>',
                        '<button class=\'text-blue-600 hover:text-blue-800 dark:text-blue-400 text-sm font-medium\'>View</button>'
                    ],
                    [
                        '<span class=\'font-medium text-gray-900 dark:text-white\'>User Engagement Report</span><br><span class=\'text-sm text-gray-500 dark:text-gray-400\'>User activity and engagement metrics</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Sep 28, 2024</span>',
                        '<span class=\'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400\'>Completed</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Admin User</span>',
                        '<button class=\'text-blue-600 hover:text-blue-800 dark:text-blue-400 text-sm font-medium\'>View</button>'
                    ],
                    [
                        '<span class=\'font-medium text-gray-900 dark:text-white\'>Revenue Forecast</span><br><span class=\'text-sm text-gray-500 dark:text-gray-400\'>Revenue projections for next quarter</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Sep 20, 2024</span>',
                        '<span class=\'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400\'>Processing</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Admin User</span>',
                        '<button class=\'text-blue-600 hover:text-blue-800 dark:text-blue-400 text-sm font-medium\'>View</button>'
                    ],
                    [
                        '<span class=\'font-medium text-gray-900 dark:text-white\'>Traffic Analysis</span><br><span class=\'text-sm text-gray-500 dark:text-gray-400\'>Website traffic sources and behavior</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Sep 15, 2024</span>',
                        '<span class=\'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400\'>Failed</span>',
                        '<span class=\'text-sm text-gray-600 dark:text-gray-400\'>Admin User</span>',
                        '<button class=\'text-blue-600 hover:text-blue-800 dark:text-blue-400 text-sm font-medium\'>Retry</button>'
                    ],
                ]"
                :striped="true"
                :hover="true"
            >
                <x-slot name="footer">
                    <div class="flex items-center justify-between">
                        <p class="text-sm text-gray-600 dark:text-gray-400">Showing 1 to 4 of 24 reports</p>
                        <div class="flex gap-2">
                            <x-ui.button size="sm" variant="outline">Previous</x-ui.button>
                            <x-ui.button size="sm" variant="outline">Next</x-ui.button>
                        </div>
                    </div>
                </x-slot>
            </x-data.table>
        </x-ui.card>
    </div>

    <script>
        // Initialize charts after the page loads
        document.addEventListener('DOMContentLoaded', function() {
            // Revenue Chart
            const revenueCtx = document.getElementById('revenueChart').getContext('2d');
            new Chart(revenueCtx, {
                type: 'line',
                data: {
                    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    datasets: [{
                        label: 'Revenue',
                        data: [6500, 7800, 8200, 9500, 8800, 9200, 11500, 10200, 12500, 14580, 13200, 15800],
                        borderColor: '#4f46e5',
                        backgroundColor: 'rgba(79, 70, 229, 0.1)',
                        tension: 0.4,
                        fill: true
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });

            // Users Chart
            const usersCtx = document.getElementById('usersChart').getContext('2d');
            new Chart(usersCtx, {
                type: 'bar',
                data: {
                    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                    datasets: [{
                        label: 'New Users',
                        data: [240, 380, 320, 450, 380, 520, 680, 520, 748, 848, 780, 920],
                        backgroundColor: '#10b981',
                        borderRadius: 4
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        });
    </script>
</x-layout.layout>
